#!/bin/sh

# LAST EDITED: 10/22/2014
# Needs major update!

# This script makes installing programs in Linux super easy.
# To make this script excutable copy/paste the following into a terminal:
# sudo chmod +x install_script
# Then to run type:
# ./install_script
# Or you could just right click the script, and go to "Permisisons" and then check
# "Excutable"...

# Follow this site:
# https://sites.google.com/site/easylinuxtipsproject/ssd

# Add a few repos - uncomment on first install
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo add-add-repository ppa:danielrichter2007/grub-customizer
sudo add-add-repository ppa:webupd8team/sublime-text-3
sudo apt-add-repository ppa:pipelight/stable

# Update the repos.
sudo apt-get -y update

# *******************
# Get quicktile stuff
# *******************
sudo apt-get -y install python python-gtk2 python-xlib python-dbus python-wnck git

# Might need to get this stuff too?
wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python

# MAKE SURE TO DOWNLOAD QUICKTILE.
git clone https://github.com/ssokolow/quicktile.git ~/Quicktile

# Then run the following from the quicktile folder (~/quicktile/):
cd ~/Quicktile
sudo ./setup.py install

# Also change the keybindings to "Shift" instead of "Alt"!
# And use the auto_start_quicktile script to get it to autorun.
# Also make an autostart entry in the session settings page.

# ****************************************************************
#  Razer Death Adder Config stuff (Only the command line works...)
#  Also don't forget to use the autostart razer script!
# ****************************************************************
sudo apt-get -y install python3 libusb-1.0.0-dev python-pyside cmake

# Update Locale so underscores show up first
sudo update-locale LC_COLLATE=C

# Screensaver for Xubuntu
sudo apt-get -y install xscreensaver xscreensaver-gl-extra xscreensaver-data-extra

# Get Sublime (also awesome)
sudo apt-get -y install sublime-text-installer

# Useful tools
sudo apt-get -y install gksu leafpad synaptic gdebi linux-firmware-nonfree

# Programming stuff
sudo apt-get -y install g++ openjdk-6-jdk gedit curl geany

# System monitors - just cuz there awesome.
sudo apt-get -y install nmon glances htop lm-sensors hddtemp \
psensor lm-sensors hddtemp psensor gsmartcontrol

# NETFLIX!!
sudo apt-get -y install wine
sudo apt-get -y install pipelight-multi 
sudo pipelight-plugin --enable silverlight
sudo apt-get -y install netflix-desktop

# Disk related
sudo apt-get -y install grub-customizer gparted transmission filezilla rsync unetbootin 

# Fun stuff.
sudo apt-get -y steam pinta gimp vlc neverball teg pychess shutter google-chrome-stable \
shutter sl

# Security
sudo apt-get -y keepassx clamav nmap wireshark virtualbox

# Office
sudo apt-get -y libreoffice

# Macros
sudo apt-get -y xnee gnee cnee xmacroshut up huy
