#!/bin/sh

# This script makes installing programs in Linux super easy.
# To make this script excutable copy/paste the following into a terminal:
# sudo chmod +x install_script
# Then to run type:
# ./install_script
# Or you could just right click the script, and go to "Permisisons" and then check
# "Excutable"...

# Follow this site:
# https://sites.google.com/site/easylinuxtipsproject/ssd

# Add a few repos - uncomment on first install
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo add-apt-repository ppa:danielrichter2007/grub-customizer
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-add-repository ppa:pipelight/stable

# Update the repos.
sudo apt-get update

# *******************
# Get quicktile stuff
# *******************
sudo apt-get install python python-gtk2 python-xlib python-dbus python-wnck

# Might need to get this stuff too?
wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python

# MAKE SURE TO DOWNLOAD QUICKTILE.
git clone https://github.com/ssokolow/quicktile.git ~/Quicktile

# Then run the following from the quicktile folder (~/quicktile/):
cd ~/Quicktile
sudo ./setup.py install

# Also change the keybindings to "Shift" instead of "Alt"! 

# Maybe need to run this on startup?
# quicktile.py --daemonize
# Actually, use the auto_start_quicktile script to get it to autorun.
# Just make an autostart entry in the session settings page.

# ****************************************************************
#  Razer Death Adder Config stuff (Only the command line works...)
#  Also don't forget to use the autostart razer script!
# ****************************************************************
sudo apt-get install python3 libusb-1.0.0-dev python-pyside cmake

# Update Locale so underscores show up first
sudo update-locale LC_COLLATE=C

# Screensaver for Xubuntu
sudo apt-get install xscreensaver xscreensaver-gl-extra xscreensaver-data-extra

# Get Sublime
sudo apt-get install sublime-text-installer

# Useful tools
sudo apt-get install gksu leafpad synaptic gdebi linux-firmware-nonfree \
g++

# NETFLIX!!
sudo apt-get install pipelight-multi
sudo pipelight-plugin --enable silverlight
sudo apt-get install netflix-desktop

# M A G I C
# Mass installs all the programs I use. Add more as I find them!
sudo apt-get install grub-customizer steam gparted git neverball teg shutter \
keepassx transmission libreoffice vlc gimp terminator guake wine nmap \
wireshark virtualbox curl gedit google-chrome-stable filezilla pychess \
grsync rsync unetbootin sl gsmartcontrol clamav geany sensors lm_sensors \